Add lesson3 part 1
HoroshoNaVolge/dotnetLearning pull request #5
Opened 2024-02-17 14:02 UTC by HoroshoNaVolge

Add part 1 of the task:
Урок 1. Часть 2. Использование стороннего API. Реализация WebApi на ASP.NET Core, использование websockets
Задание: реализовать консольное приложение, которое единственным параметром будет принимать ИНН организации, и печатать название организации, которое оно получит от [сервиса DaData](https://dadata.ru/api/find-party/). То есть нужно разобраться в их API, зарегистрироваться (сервис бесплатный для небольших масштабов), составить запрос и реализовать это на C# Рекомендуется установить и использовать Fiddler/Postman или другой аналогичный инструмент.

2024-02-17 14:56 UTC, navferty requested changes

2024-02-17 14:56 UTC, navferty commented on Other/LearnWebApi.cs
> +            GetAsync(client).Wait();
Рекомендую всегда избегать синхронного вызова асинхронных операций. Если метод возвращает `Task` или `Task<T>`, результат следует `await`-ить:

```c#
var response = await GetAsync(client);
```

Также это потребует изменения и того, как объявлен сам метод, где происходит вызов: изменить тип возвращаемого значения (вместо `void` будет `Task`, вместо какого-то типа `T` - `Task<T>`, а также добавления ключевого слова `async`:

```c#
static async Task Run()
{
   // ...
}
```

Я недавно записывал [видос про асинк-эвейт](https://www.youtube.com/watch?v=pYWIfLZ7obY), рекомендую познакомиться. В описании к видео есть еще полезные ссылки.

2024-02-17 14:56 UTC, navferty commented on Other/LearnWebApi.cs
> +        private static HttpClient? _httpClient;
Приватные поля рекомендуется объявляеть до конструктора. StyleCop анализатор [рекомендует](https://github.com/DotNetAnalyzers/StyleCopAnalyzers/blob/master/documentation/SA1201.md) придерживаться такого порядка членов класса:

* поля
* конструкторы
* свойства
* методы

2024-02-17 14:56 UTC, navferty commented on Other/LearnWebApi.cs
> +            if (_httpClient == null)
Вместо отдельного метода, инициализирующего поля, можно использовать непосредственно синтаксис [инициализации поля](https://learn.microsoft.com/en-us/dotnet/csharp/programming-guide/classes-and-structs/fields):

```c#
private static HttpClient? _httpClient = new();
```

Кроме того, в нынешнем виде метод инициализации может привести к ошибке:

```c#
var client1 = GetHttpClient("http://example1.com");

// вопреки ожиданиям, client2 будет использовать адрес example1.com
var client2 = GetHttpClient("http://example2.com");
```

2024-02-17 14:56 UTC, navferty commented on Other/LearnWebApi.cs
> +            try { response.EnsureSuccessStatusCode(); }
Если заглянуть в исходный код этого метода, можно увидеть, что происходит провека через публичное свойство `IsSuccessStatusCode`, и в случае неудачи выбрасывается исключение:
![image](https://github.com/HoroshoNaVolge/dotnetLearning/assets/20906347/03edf152-0e4b-4480-9f89-387a11236820)

Поэтому нет никакого смысла вызывать этот код, чтобы сразу же подавить выброшенное исключение: вместо этого можно напрямую обратиться к свойству `IsSuccessStatusCode`. Надо заметить, что выбрасывание исключение - сравнительно дорогая операция с точки зрения производительности.

2024-02-17 14:56 UTC, navferty commented on dotnetLearning.csproj
> +    <Reference Include="Microsoft.Office.Interop.Excel">
Возможно, эта ссылка на interop excel была добавлена по ошибке? Кажется, в проекте не используется взаимодействие с приложением MS Excel

2024-02-17 14:56 UTC, navferty commented on Program.cs
>      static void Main(string[] args)
Начиная с версии 7.1 языка C#, метод `Main` (точка входа в программу) [может быть асинхронным](https://github.com/dotnet/csharplang/blob/main/proposals/csharp-7.1/async-main.md), поэтому нет необходимость в блокирующем вызове `.Wait();` для ожидания результата асинхронного вызова.

2024-02-17 14:56 UTC, navferty commented on Lesson3/Lesson3.cs
> +                Console.WriteLine(response.suggestions[0].value);
Что будет, если предложений не будет (пустой массив `suggestions`)?

2024-02-17 14:56 UTC, navferty commented on Lesson3/Lesson3.cs
> +                var token = "bbc8e57adbc7bebaf5265017740c30fce634cdc0";
Как правило, не рекомендуется оставлять в исходном коде ключи, в том числе к внешним сервисам. В данной ситуации не очень срашно, но на будущее (начиная с приложения ASP.NET Web API) рекомендую использовать файл `appsettings.json` для хранения ключей (и читать конфигурацию через [IConfiguration](https://learn.microsoft.com/en-us/dotnet/core/extensions/configuration)). Пока сильно не заморачивайся, это для информации, на будущее.

2024-02-17 14:56 UTC, navferty commented on Other/LearnWebApi.cs
> +            var jsonResponse = await response.Content.ReadAsStringAsync();
В данном случае происходит сначала чтение ответа в виде строки в память, с дальнейшей передачей этой строки в десериализатор JSON. `JsonSerializer` [поддерживает работу со `Stream`-ом](https://makolyte.com/csharp-deserialize-json-as-a-stream/), то есть потоковую обработку входящих данных:

```c#
var contentStream = await response.Content.ReadAsStreamAsync();
var result = await JsonSerializer.DeserializeAsync<List<Todo>>(contentStream);
```

2024-02-17 16:38 UTC, HoroshoNaVolge commented on Lesson3/Lesson3.cs
> +                var token = "bbc8e57adbc7bebaf5265017740c30fce634cdc0";
пока не трогаю

2024-02-17 18:26 UTC, HoroshoNaVolge commented on Other/LearnWebApi.cs
> +            var jsonResponse = await response.Content.ReadAsStringAsync();
крашится на преобразовании JSON в List<Todo> (по адресу JSON на 1 объект)
            using HttpResponseMessage response = await httpClient.GetAsync(path);
            if (response.IsSuccessStatusCode)
            {
                var contentStream = await response.Content.ReadAsStreamAsync();
                // Не могу понять почему не десериализует из потока json в List<ToDo> 
                var result = await JsonSerializer.DeserializeAsync<List<Todo>>(contentStream);
            }

2024-02-17 20:14 UTC, HoroshoNaVolge commented on Other/LearnWebApi.cs
> +            var jsonResponse = await response.Content.ReadAsStringAsync();
исправил, работает

2024-02-17 21:33 UTC, navferty commented on Lesson3/Lesson3.cs
> +                    Console.WriteLine(response.suggestions[0].value);
Можно упростить, используя метод linq `FirstOrDefault()`: https://learn.microsoft.com/ru-ru/dotnet/api/system.linq.enumerable.firstordefault?view=net-7.0

2024-02-17 21:33 UTC, navferty commented on Other/LearnWebApi.cs
> +            await Console.Out.WriteAsync("\nВыполняется получение множества объектов через HttpResponseMessage:\n");
Чтобы не нужно было явно передавать всякий раз символ переноса строки, можно использовать метод WriteLine, в котором перенос строки добавляется автоматически.

2024-02-17 21:33 UTC, navferty commented on Other/LearnWebApi.cs
> +                  string jsonContent = await reader.ReadToEndAsync();
Попробуй не читать в промежуточный результат как строку. JsonSerializer может сразу принимать стрим. То есть не нужно будет выделять память под весь ответ целиком в виде строки.

Представь, что ответ очень большой - например, несколько мегабайт. Если ты читаешь в строку, потребуется дождаться полностью всех пакетов ответа, собрать тело ответа и всё это записать в строку в оперативной памяти.

Если же открыть `Stream`, то можно передать его сразу в десериализатор. В этом случае, возможно выиграть в использованной памяти: можно будет начать десериализацию первых элементов листа даже еще до того, как последние пакеты (содержащие часть тела ответа) дойдут до нашей сетевой карты. Возможно, желательно будет изменить тип, в который происходит десериализация, вместо `List<T>` указать `IEnumerable<T>`. Второй тип не требует материализации в памяти всего списка элементов, позволяя лишь итерироваться по объектам коллекции (например в цикле `foreach`).

В приведённом ниже примере, мы позволяем читать ответ последовательно, получая элемент за элементом, не дожидаясь окончания ответа. На очень больших коллекциях это может быть единственным вариантом, который позволит "влезть" в имеющуюся оперативную память:

```c#
var response = await GetVeryBigResponse();
using var stream = await response.Content.ReadAsStreamAsync();
var items = JsonSerializer.DeserializeAsyncEnumerable<T>(stream);

await foreach (var item in items)
{
    // process current item
}
```

В частности, такой подход может быть особенно полезен при чтении и обработке очень больших файлов (например, огромный csv на миллионы записей). Потоковая обработка не потребует ни в какой момент времени загрузки всего содержимого в память.

2024-02-17 21:33 UTC, navferty commented on Other/LearnWebApi.cs
> +using System.Security.Cryptography;
Неймспейс не используется?

2024-02-18 15:42 UTC, navferty approved these changes

2024-02-18 15:42 UTC, navferty commented on Other/LearnWebApi.cs
> +                if (jsonDocument.RootElement.ValueKind == JsonValueKind.Array)
Это ок для учебного проекта, чтобы разобраться с устройством `JsonDocument`, и динамически десериализовывать в соответствующий тип.
Но хотел бы предостеречь от использования подобного подхода в продакшне. В 99% случаев ожидаемая структура ответа заранее известна, а при её изменении лучшим вариантом будет выбросить исключение, чем пытаться парсить неожиданный ответ от внешнего сервиса.

2024-02-18 15:42 UTC, navferty commented on Other/IEnumerableLearn.cs
> +    internal class IEnumerableLearnWithOwnEnumerator : IEnumerable<int>
Для сведения:

Иногда для простоты в одном и том же классе совмещают реализации обоих интерфейсов:

```c#
class IEnumerableLearnWithOwnEnumerator : IEnumerable<int>, IEnumerator<int>
{
    public IEnumerator<int> GetEnumerator() => this;
    IEnumerator IEnumerable.GetEnumerator() => GetEnumerator();

    // остальная реализация логики IEnumerator
}
```

2024-02-18 15:42 UTC, navferty commented on Other/IEnumerableLearn.cs
> +    internal class IEnumerableLearn : IEnumerable<int>
👍

2024-02-18 15:44 UTC, HoroshoNaVolge commented on Other/LearnWebApi.cs
> +                if (jsonDocument.RootElement.ValueKind == JsonValueKind.Array)
Понял, спасибо!

2024-02-18 16:58 UTC, merged